### ISSUE TITLE
刚安装好，要运行提示要创建wukong/config.yml 一直创建不成功？怎么办？

### ISSUE THREAD

**Issue by ptzj** [musistudio/wukong-robot-install-script#12]
![QQ截图20200207200533](https://user-images.githubusercontent.com/25528507/74028511-6fc8f200-49e5-11ea-9349-fda7e6f1af0c.jpg)
刚安装好，要运行提示要创建wukong/config.yml 一直创建不成功？怎么办？

**Comment by musistudio** [comment]
输入y按回车会自动创建


------------------------------------------------------------------
发件人：ptzj <notifications@github.com>
发送时间：2020年2月7日(星期五) 20:07
收件人：musistudio/wukong-robot-install-script <wukong-robot-install-script@noreply.github.com>
抄　送：Subscribed <subscribed@noreply.github.com>
主　题：[musistudio/wukong-robot-install-script] 刚安装好，要运行提示要创建wukong/config.yml 一直创建不成功？怎么办？ (#12)

[QQ截图20200207200533]
 刚安装好，要运行提示要创建wukong/config.yml 一直创建不成功？怎么办？

**Comment by ptzj** [comment]
不行，报错，而且该文件夹下没看到该文件，而且报错，方便我加您的QQ吗？我是45039535，谢谢

**Comment by ptzj** [comment]
********************************************************
*          wukong-robot - 中文语音对话机器人           *
*          (c) 2019 潘伟洲 <m@hahack.com>              *
*     https://github.com/wzpan/wukong-robot.git        *
********************************************************

            如需退出，可以按 Ctrl-4 组合键。


2020-02-07 20:41:55,487 - robot.ASR - INFO - 使用 baidu-asr ASR 引擎
2020-02-07 20:41:55,565 - robot.AI - INFO - 使用 emotibot 对话机器人
2020-02-07 20:41:55,720 - robot.TTS - INFO - 使用 baidu-tts TTS 引擎
2020-02-07 20:41:55,798 - robot.NLU - INFO - 使用 unit NLU 引擎
2020-02-07 20:41:55,878 - robot.plugin_loader - INFO - 插件 Camera 已被禁用
2020-02-07 20:41:55,880 - robot.plugin_loader - INFO - 插件 CleanCache 加载成功
2020-02-07 20:41:55,967 - robot.plugin_loader - INFO - 插件 Email 加载成功
2020-02-07 20:41:56,009 - robot.plugin_loader - INFO - 插件 LocalPlayer 加载成功                                                                                        
2020-02-07 20:41:56,012 - robot.plugin_loader - INFO - 插件 Poem 加载成功
2020-02-07 20:41:56,054 - robot.plugin_loader - INFO - 插件 BaiduFM 加载成功
2020-02-07 20:41:56,058 - robot.plugin_loader - INFO - 插件 BaiduMap 加载成功
2020-02-07 20:41:56,090 - robot.plugin_loader - INFO - 插件 ControMqtt 加载成功
2020-02-07 20:41:56,092 - robot.plugin_loader - INFO - 插件 Direction 加载成功
2020-02-07 20:41:56,095 - robot.plugin_loader - INFO - 插件 EmailMyPC 加载成功
2020-02-07 20:41:56,097 - robot.plugin_loader - INFO - 插件 Halt 加载成功
2020-02-07 20:41:56,099 - robot.plugin_loader - INFO - 插件 Hass 加载成功
2020-02-07 20:41:56,101 - robot.plugin_loader - INFO - 插件 HeadlineNews 加载成                                                                                        功
2020-02-07 20:41:56,104 - robot.plugin_loader - INFO - 插件 Lamp 加载成功
2020-02-07 20:41:56,107 - robot.plugin_loader - WARNING - 插件 NeteaseMusic 加载                                                                                        出错，跳过
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/plugin_loader.py", line 36, in init_plugins
    mod = loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrappe                                                                                        r
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.wukong/contrib/NeteaseMusic.py", line 9, in <module>
    from robot.Player import MusicPlayer
ImportError: cannot import name 'MusicPlayer' from 'robot.Player' (/home/pi/wuko                                                                                        ng-robot/robot/Player.py)
2020-02-07 20:41:56,113 - robot.plugin_loader - INFO - 插件 RaspberryPiStatus 加                                                                                        载成功
2020-02-07 20:41:56,116 - robot.plugin_loader - INFO - 插件 Reboot 加载成功
2020-02-07 20:41:56,118 - robot.plugin_loader - INFO - 插件 RoadCondition 加载成                                                                                        功
2020-02-07 20:41:56,120 - robot.plugin_loader - INFO - 插件 SmartMiFan 加载成功
2020-02-07 20:41:56,123 - robot.plugin_loader - INFO - 插件 SpeakIP 加载成功
2020-02-07 20:41:56,125 - robot.plugin_loader - INFO - 插件 SpeakTemperature 加                                                                                        载成功
2020-02-07 20:41:56,127 - robot.plugin_loader - INFO - 插件 WOL 加载成功
2020-02-07 20:41:56,207 - robot.plugin_loader - INFO - 插件 Weather 已被禁用
2020-02-07 20:41:56,210 - robot.plugin_loader - WARNING - 插件 WeiBo 加载出错，                                                                                        跳过
Traceback (most recent call last):
  File "/home/pi/wukong-robot/robot/plugin_loader.py", line 36, in init_plugins
    mod = loader.load_module(name)
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrappe                                                                                        r
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/.wukong/contrib/WeiBo.py", line 4, in <module>
    from sdk.weibo import WeiBo
ModuleNotFoundError: No module named 'sdk'
2020-02-07 20:41:56,213 - robot.plugin_loader - INFO - 插件 YouDaoFanYi 加载成功                                                                                        
2020-02-07 20:41:56,216 - robot.Brain - INFO - 已激活插件：['cleancache', 'email                                                                                        ', 'LocalPlayer', 'poem', 'baidufm', 'BaiduMap', 'mqttPub', 'direction', 'emailm                                                                                        ypc', 'halt', 'hass', 'headline_news', 'Lamp', 'pi_status', 'reboot', 'roadcondi                                                                                        tion', 'SmartMiFan', 'speak_ip', 'speak_temperature', 'wol', 'youdao']
2020-02-07 20:41:56,257 - robot.Conversation - INFO - 命中缓存，播放缓存语音
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPer                                                                                        iodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPer                                                                                        iodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 924
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPer                                                                                        iodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPer                                                                                        iodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
Expression 'alsa_snd_pcm_hw_params_set_period_size_near( pcm, hwParams, &alsaPer                                                                                        iodFrames, &dir )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 934
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bl                                                                                        uealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or di                                                                                        rectory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bl                                                                                        uealsa.device'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned err                                                                                        or: No such file or directory
ALSA lib conf.c:5036:(snd_config_expand) Args evaluate error: No such file or di                                                                                        rectory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                        k
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                        k
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                        k
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                        k
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_a52.c:823:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib conf.c:5014:(snd_config_expand) Unknown parameters {AES0 0x6 AES1 0x82                                                                                         AES2 0x0 AES3 0x2  CARD 0}
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM iec958:{AES0 0x6 AES1 0x                                                                                        82 AES2 0x0 AES3 0x2  CARD 0}
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                        k
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                        k

**Comment by ptzj** [comment]
启动过程是这样，然后就卡在那边不动了~
