### ISSUE TITLE
启动缺少aip

### ISSUE THREAD

**Issue by fingermaker** [musistudio/wukong-robot-install-script#16]
安装均没有问题，但是运行的时候出现如下代码：
Traceback (most recent call last):
  File "wukong.py", line 7, in <module>
    from robot.Conversation import Conversation
  File "/home/pi/wukong-robot/robot/Conversation.py", line 12, in <module>
    from robot import logging, ASR, TTS, NLU, AI, Player, config, constants, utils, statistic
  File "/home/pi/wukong-robot/robot/ASR.py", line 3, in <module>
    from aip import AipSpeech
ModuleNotFoundError: No module named 'aip'

**Comment by fingermaker** [comment]
安装的时候有一个这个错误：
![image](https://user-images.githubusercontent.com/29058113/95644725-1e7c7f80-0aeb-11eb-919d-040395176984.png)

**Comment by Scrooge2** [comment]
解决了吗
