### ISSUE TITLE
在Ubuntu16.04上一键安装完毕后无法正常启动

### ISSUE THREAD

**Issue by 1606701** [musistudio/wukong-robot-install-script#3]
root@ubuntu:/home/cm/wukong/wukong-robot-master# python3 wukong.py
Traceback (most recent call last):
  File "/home/cm/wukong/wukong-robot-master/snowboy/snowboydetect.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'snowboy._snowboydetect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wukong.py", line 2, in <module>
    from snowboy import snowboydecoder
  File "/home/cm/wukong/wukong-robot-master/snowboy/snowboydecoder.py", line 5, in <module>
    from . import snowboydetect
  File "/home/cm/wukong/wukong-robot-master/snowboy/snowboydetect.py", line 17, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/cm/wukong/wukong-robot-master/snowboy/snowboydetect.py", line 16, in swig_import_helper
    return importlib.import_module('_snowboydetect')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_snowboydetect'

**Comment by musistudio** [comment]
脚本在执行的过程中有没有报错？如果脚本无法正常运行的话你可以尝试一下手动编译snowboy

**Comment by 1606701** [comment]
执行过程中没报错，这个依赖关系有点多，如何手动编译snowboy，求大神指教

**Comment by musistudio** [comment]
参照文档：https://wukong.hahack.com/#/install?id=%E6%96%B9%E5%BC%8F%E4%BA%8C%EF%BC%9A%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85

**Comment by 1606701** [comment]
源项目的README里面提到了
wukong-robot 支持运行在以下的设备和系统中：

* 64bit Mac OS X
* 64bit Ubuntu（12.04 and 14.04）
* 全系列的树莓派（Raspbian 系统）
* Pine 64 with Debian Jessie 8.5（3.10.102）
* Intel Edison with Ubilinux （Debian Wheezy 7.8）
* 装有 WSL（Windows Subsystem for Linux） 的 Windows

请问大神在16.04下成功过吗

**Comment by musistudio** [comment]
成功过的

**Comment by 1606701** [comment]
解决了，是链接的库文件没有拷贝过去

**Comment by musistudio** [comment]
ok，那我关闭了
